/*
 * This source file was generated by the Gradle 'init' task
 */


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SparkEchoTest {
    @Test void someLibraryMethodReturnsTrue() {
        SparkEcho classUnderTest = new SparkEcho();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
